### ISSUE TITLE
cli (v 1.2.0) npm run dev error: Cannot find module 'html-webpack-exclude-assets-plugin'

### ISSUE THREAD

**Issue by matthewlynch** [developit/preact-cli#148]
**Description:**

After updating the cli to v1.2.0 (from v1.1.2) and running `npm run dev` I'm getting this error:

```
> preact watch

module.js:487
    throw err;
    ^

Error: Cannot find module 'html-webpack-exclude-assets-plugin'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/path/to/project/node_modules/preact-cli/lib/lib/webpack-config.js:33:39)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/path/to/project/node_modules/preact-cli/lib/commands/build.js:19:22)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! <my-project-name>@0.1.0 dev: `preact watch`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the <my-project-name>@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I've tried searching for `html-webpack-exclude-assets-plugin` inside of the `node_modules` folder and it looks like it never got installed for some reason?

To remedy the problem I tried deleting the `node_modules` folder & the `package-lock.json` file and then reinstalled everything but that didn't work 😟.

I ended up getting around the issue by running `npm install` inside of the `node_modules/preact-cli` folder and now everything seems to be working as expected.

**Info**:
os: macOS 10.12.5
node: v8.0.0
npm: 5.0.4

P.S. thank you so much for this amazing project!

**Comment by hassanbazzi** [comment]
Confirmed. Thanks for reporting!

**Comment by hassanbazzi** [comment]
https://github.com/developit/preact-cli/pull/151 Fixes this

**Comment by rkostrzewski** [comment]
Indeed an issue with preact-cli.

In the meantime for anyone affected installing the plugin via 'npm install --save-dev' should make build work.
